# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Adam Klie
first_name: Adam
last_name: Klie
email: aklie@ucsd.edu
description: >
  Schmidt AI Postdoctoral Fellow at UC San Diego. Bioinformatics, machine learning,
  and the non-coding genome. Former professional basketball player. Perpetual learner.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: bioinformatics, genomics, machine learning, deep learning, non-coding genome, UCSD, postdoc
lang: en
icon: ⚗️  # the emoji used as the favicon

url: https://adamklie.github.io
baseurl: ""
last_updated: true
impressum_path: # set to path to include impressum link in footer

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: false
search_enabled: true
socials_in_search: false
bib_search: true

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: adamklie
scholar_userid: kR9GSLMAAAAJ  # from Notion: https://scholar.google.com/citations?user=kR9GSLMAAAAJ
orcid_id: # your ORCID ID
linkedin_username: # your LinkedIn username
twitter_username: klieadam
mastodon_username: # your Mastodon handle
instagram_id: # your Instagram username

contact_note: >
  The best way to reach me is by email.

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------
google_analytics: # your Google Analytics measurement ID
cronitor_analytics: # cronitor RUM analytics
pirsch_analytics: # Pirsch Analytics site ID
openpanel_analytics: # OpenPanel analytics client ID

google_site_verification: # your google-site-verification ID
bing_site_verification: # out your bing-site-verification ID

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Adam's Blog
blog_nav_title: Blog
blog_description: Personal journey, academic reflections, and things I find interesting.
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: true
  scrollable: true
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md

keep_files:
  - CNAME
  - .nojekyll
  - .git

plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Archives
jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: /blog/:year/
    tag: /blog/tag/:name/
    category: /blog/category/:name/

# External link settings
link-attributes:
  attrs:
    target: _blank
    rel: external nofollow noopener

# Scholar settings
scholar:
  last_name: [Klie]
  first_name: [Adam, A.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_skip_fields: [abbr, abstract, arxiv, bibtex_show, blog, code, html, pdf, poster, slides, supp, video, website]
  bibtex_filters: [superscript, html_escape]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

# Deployed
